set_property PACKAGE_PIN C19 [get_ports {lightControl[0]}];
set_property PACKAGE_PIN E19 [get_ports {lightControl[1]}];
set_property PACKAGE_PIN D19 [get_ports {lightControl[2]}];
set_property PACKAGE_PIN F18 [get_ports {lightControl[3]}];
set_property PACKAGE_PIN E18 [get_ports {lightControl[4]}];
set_property PACKAGE_PIN B20 [get_ports {lightControl[5]}];
set_property PACKAGE_PIN A20 [get_ports {lightControl[6]}];
set_property PACKAGE_PIN A18 [get_ports {lightControl[7]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[0]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[1]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[2]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[3]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[4]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[5]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[6]}];
set_property IOSTANDARD LVCMOS33 [get_ports {lightControl[7]}];


set_property PACKAGE_PIN F15 [get_ports {light[0]}];
set_property PACKAGE_PIN F13 [get_ports {light[1]}];
set_property PACKAGE_PIN F14 [get_ports {light[2]}];
set_property PACKAGE_PIN F16 [get_ports {light[3]}];
set_property PACKAGE_PIN E17 [get_ports {light[4]}];
set_property PACKAGE_PIN C14 [get_ports {light[5]}];
set_property PACKAGE_PIN C15 [get_ports {light[6]}];
set_property PACKAGE_PIN E13 [get_ports {light[7]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[5]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[6]}];
set_property IOSTANDARD LVCMOS33 [get_ports {light[7]}];

set_property PACKAGE_PIN Y18 [get_ports {clk}];
set_property IOSTANDARD LVCMOS33 [get_ports {clk}];
set_property PACKAGE_PIN W4 [get_ports {start}];
set_property IOSTANDARD LVCMOS33 [get_ports {start}];